### ISSUE TITLE
Multiple inscriptions in a single transaction

### ISSUE THREAD

**Issue by haribosan** [casey/ord#1212] opened 2023-01-13 19:01 UTC
Now that #1201 has been merged, it would be interesting to explore how to inscribe multiple sats (collections) in the same transaction. I think it ultimately boils down to two options: either make an inscription per output or put all the inscriptions in the same output. Each has pros and cons, which I think can be summarized as follows:

- 1 inscription per utxo:
Pros: cleaner structure, more streamlined ordinal management and likely way easier to implement. No need to fragment a utxo when sending an inscription from a new collection.
Cons: fees for minting are proportional to the number of items in a collection; these need to be payed upfront, and collections made of thousands of items might get very expensive for creators to inscribe. Not sure if this is actually a positive feature compared to other platforms like eth (along the lines of: more expensive hence less frivolous?), but at a first glance it looks like a downside.

- Multiple inscriptions per utxo:
Pros: fees for minting are independent of the size of a collection, because only one utxo is created. This means much lower upfront costs for creators, especially when it comes to large collections.
Cons: the utxo containing the whole collection will need to be fragmented whenever an item is transferred from it. Assuming 1 change utxo (with all the remaining items) for each transfer, creators costs are comparable to the 1inscription=1utxo model; they’re just spread thin over time. But one upside is that fees are lower when transferring a subset of (consecutive) items.

Not sure if there are other more efficient ways to organize inscriptions inside utxos.

**Comment by casey** [comment] 2023-01-13 19:08
Good summary! This is a dupe of #876, I'll reply there.

**Closed by casey** 2023-01-13 19:08 UTC
