### ISSUE TITLE
My inscriptions is taking way too long

### ISSUE THREAD

**Issue by mzkworks** [casey/ord#1653] opened 2023-02-10 17:41 UTC
I've set the fee to 8.0 and it's taking very long. I've also minted the previous ones with the same fee for minutes.
What is this happening and how to avoid it in the future? Also can I stop it?

The issue inscription:
https://mempool.space/tx/d2d0cefc353cb1fe6f44a2d66b7f2eeef7d5df9769311485de0643ea4dcd1ac7

Previous inscription that took 3-5min:
https://mempool.space/tx/7998a7ea1f9d6a844eab2e6c863d1be30189ca281c369d7f25e9be6f05b8a82a

I've read somewhere that it may not respect the fee command, could this be the issue? Or should I use more fee, like 20.0?

Thank you!

**Comment by dude513** [comment] 2023-02-10 18:51
There are 40K unconfirmed transactions in the mempool currently, it will take slightly longer to be included in the newly created block, depending on the network activity.

**Comment by raphjaph** [comment] 2023-02-21 22:13
Closing, since inscription confirmed now

**Closed by raphjaph** 2023-02-21 22:13 UTC
