### ISSUE TITLE
Ord explorer returns "Internal Server Error" when trying to display inscription

### ISSUE THREAD

**Issue by aviwol** [casey/ord#1902] opened 2023-03-08 23:53 UTC
When trying to access some inscriptions such as the one here:
```
https://ordinals.com/inscription/59609c9923db0011599ed5d0034df899174b2ce7bf6e02dfbb678d7ce2ecb987i0
```

The server will return an HTTP error 500 with the error "Internal Server Error".
When checking the server logs:

```
ord-docker-proxy-1  | 2023/03/08 23:44:45 {"method":"getrawtransaction","params":["59609c9923db0011599ed5d0034df899174b2ce7bf6e02dfbb678d7ce2ecb987",false],"id":41,"jsonrpc":"2.0"}
ord-docker-proxy-1  | 2023/03/08 23:44:45 {"jsonrpc":"2.0","result":"01000000000101aa3bea9d6e1d9984ffff52e824ecde1b6fc92885608c9a2abbd45884224089930000000000fdffffff01102700000000000022512071397602bc0b97f5abda124604737caca6385490b7d0f2e40a730c5a07810f350340ec9fe0b4f8c2d491583e4292cb757261e539652866a24ceca8d5362e7ce442120966f107db9022cb8b0d4867275b5f3d7ebc271456357d8074c8e16b194b60e870209cd67a414b3f2727dc2af84b60205c55cf4d7de7b7281ca89ebc7e9ff0316952ac0063036f7264010118746578742f706c61696e3b636861727365743d7574662d38002a7b2270223a22736e73222c226f70223a22726567222c226e616d65223a2236383639382e73617473227d6821c09cd67a414b3f2727dc2af84b60205c55cf4d7de7b7281ca89ebc7e9ff031695200000000","error":null,"id":41}
ord-docker-proxy-1  | 
ord-docker-proxy-1  | 2023/03/08 23:44:45 {"method":"getrawtransaction","params":["0000000000000000000000000000000000000000000000000000000000000000",false],"id":42,"jsonrpc":"2.0"}
ord-docker-proxy-1  | 2023/03/08 23:44:45 {"jsonrpc":"2.0","result":null,"error":{"code":-5,"message":"No information available about transaction 0000000000000000000000000000000000000000000000000000000000000000"},"id":42}
ord-docker-proxy-1  | 
ord-docker-ord-1    | error serving request: JSON-RPC error: RPC error response: RpcError { code: -5, message: "No information available about transaction 0000000000000000000000000000000000000000000000000000000000000000", data: None }
```

It looks like it is for some reason trying to read tx `0000000000000000000000000000000000000000000000000000000000000000` which fails.

This is only for a few specific inscriptions. 
Seems like a bug but any help would be appreciated.

**Comment by tyjvazum** [comment] 2023-03-09 00:03
If you know of other inscriptions, can you provide a list by inscription number?

**Comment by aviwol** [comment] 2023-03-09 10:40
More examples I have found:
- https://ordinals.com/inscription/ebfc364d43e6f921bc9aff3831340e1b06f8c813cb6fbb8a6a54aa26a8f80497i0
- https://ordinals.com/inscription/1b63cf1b872851da4bb99bb327ee8bd293687046674d96ba384d6104bbef16f9i0
- https://ordinals.com/inscription/b6ad2b77f26d31d3fccae95c0ab813460bf7dcfc6402b078bafee97322891156i0

I'm sure there are more.

**Comment by rot13maxi** [comment] 2023-03-09 14:47
Do you have txindex turned on for bitcoind?

**Comment by aviwol** [comment] 2023-03-09 14:50
@rot13maxi yes. The issue shows up also in the main ordinals.com explorer.

**Comment by tyjvazum** [comment] 2023-03-09 16:29
It seems like this could be related to these issues: https://github.com/casey/ord/issues/1881, https://github.com/casey/ord/issues/1455#issuecomment-1435049264

**Comment by veryordinally** [comment] 2023-03-24 17:12
Duplicate of #1841

**Closed by veryordinally** 2023-03-24 17:12 UTC
