### ISSUE TITLE
Add ability to prove ownership of an inscription

### ISSUE THREAD

**Issue by wagmiwiz** [casey/ord#1610] opened 2023-02-08 23:33 UTC
I am aware that this may not be possible due to bitcoin core limitations with taproot descriptors, but ideally the workflow is something like:

1. Alice requests Bob to prove they own inscription X by signing it with a message Y
2. Bob does `ord wallet signmessage <inscription id> <message>` and sends signature to Alice
3. Alice does `ord wallet verifymessage <inscription id> <message> <signature>`

This would enable various tooling to be built (such as Discord bots for holder roles, increased trust for OTC trades etc)

What is the current blocker to having this done? Or is there a better way to prove inscription ownership?

**Comment by casey** [comment] 2023-02-08 23:34
Great comment, but this is a dupe of #1462, check out that issue. I think main blocker is bitcoin taproot message hasn't been designed.

**Closed by casey** 2023-02-08 23:34 UTC

**Comment by wagmiwiz** [comment] 2023-02-08 23:48
Thanks, not sure how I missed that one.
