### ISSUE TITLE
Rocktoshi will not sell me a rock

### ISSUE THREAD

**Issue by hashbender** [casey/ord#1789] opened 2023-02-18 03:32 UTC
Will the devs please do something?

This demonstrates a state level attack.  They are trying to 51% the ord network which degrades the value of fungible sound money.

**Comment by cryppadotta** [comment] 2023-02-18 04:40
Unable to reproduce. When I tried to buy, it worked just fine 

![F8C58B30-4063-4749-ADCE-D7F03332E1A3](https://user-images.githubusercontent.com/34892728/219834450-ab588611-34a6-4590-b728-620d86fa3771.jpeg)

**Comment by cbspears** [comment] 2023-02-18 05:21
Hey I created a GitHub account just to come out against this proposal.

**Comment by shanghigh** [comment] 2023-02-18 12:16
Does sats=null?

**Comment by rocktoshi** [comment] 2023-02-18 13:17
We present this as a more affordable option for @hashbender: 

![image](https://user-images.githubusercontent.com/125731749/219867950-14fbda73-0f60-488f-b405-cd2b7ccf2557.png)

**Comment by Psifour** [comment] 2023-02-23 12:13
It would appear this issue has been resolved. User @hashbender was seen bidding on a fancy rock that is being auctioned on the Ordinal Hub discord. 

Please close the issue or provide additional context to assist in further isolating the issue.

**Closed** 2023-03-20 15:12 UTC
