### ISSUE TITLE
psa: reorg detected at or before 783830, software nonfunctional due to reorg bug, stated solution is to do full reindex

### ISSUE THREAD

**Issue by 0attack** [casey/ord#1946] opened 2023-03-18 17:06 UTC
[update] another reorg occurred at 783830, the ordinals.com website is broken, anyone running the cli program during the reorg will likely see the error message and need to do a full reindex again...

psa for anyone experiencing `error: reorg detected at or before 781277` which should be everyone that regularly ran the cli program before yesterday. the ordinals.com website is broken but reindexing to get back up. nothing can be viewed and no inscriptions can be made. stated [solution](https://github.com/casey/ord/issues/1945#issuecomment-1474887671) is to reindex from scratch. no software fix planned currently.

being discussed in https://github.com/casey/ord/issues/148 and https://github.com/casey/ord/issues/1945

this issue serves as a call to at least make the reindexing automatic in cases of a reorg error. it will happen again and again. handling it in some way would reduce user confusion. it should be some easy code changes to make. can anyone write the code for it?

**Comment by DanielHook15** [comment] 2023-03-18 18:11
As apezord mentions in https://github.com/casey/ord/issues/148, it is even possible that we lose artifacts, but I do not known the details or how to avoid that.

**Comment by nammaki** [comment] 2023-03-21 23:39
Someone please explain how to reindex 🙏

**Comment by DanielHook15** [comment] 2023-03-23 00:06
You have to rename or delete the file index.redb. ord will then create a new index file.

**Comment by nammaki** [comment] 2023-03-23 17:29
> You have to rename or delete the file index.redb. ord will then create a new index file.

Thank you 🤗

**Comment by soenkehahn** [comment] 2023-04-24 21:12
Very much agreed, `ord` should handle reorgs. Closing as duplicate of #148.

**Closed by soenkehahn** 2023-04-24 21:12 UTC
