### ISSUE TITLE
Unable to connect to a valid Bitcoin Core RPC

### ISSUE THREAD

**Issue by merc1er** [casey/ord#1614] opened 2023-02-09 03:30 UTC
I am getting the following error:

```
➜  ~ ord --rpc-url "https://nd-8xxx.p2pify.com/xxx" wallet receive
error: failed to connect to Bitcoin Core RPC at https://nd-xxx.p2pify.com/xxx
because: I/O error: No such file or directory (os error 2)
```

The RPC URL seems valid and fully synced when running `getblockchaininfo`:

```
➜  ~ curl https://nd-xxx.p2pify.com/xxx -d '{"method":"getblockchaininfo","params":[],"id":1}'

{"result":{"chain":"main","blocks":775667,"headers":775667,"bestblockhash":"00000000000000000005894974bcb811efcb64b3440cee23e75f38df18436de4","difficulty":39350942467772.63,"mediantime":1675911342,"verificationprogress":0.9999998190380068,"initialblockdownload":false,"chainwork":"00000000000000000000000000000000000000003fb1201d1fa4dd8b2595c8f0","size_on_disk":515630975843,"pruned":false,"softforks":{"bip34":{"type":"buried","active":true,"height":227931},"bip66":{"type":"buried","active":true,"height":363725},"bip65":{"type":"buried","active":true,"height":388381},"csv":{"type":"buried","active":true,"height":419328},"segwit":{"type":"buried","active":true,"height":481824}},"warnings":"Warning: unknown new rules activated (versionbit 2)"},"error":null,"id":1}
```

**Comment by EtDu** [comment] 2023-02-09 06:02
bump

**Comment by JWMatheo** [comment] 2023-02-09 07:07
before --rpc-url, you have to put --cookie-file "<YOUR_PATH>".
To find the path you have to launch bitcoind then go to the folder where the Blockchain is stored. You'll see a ".cookie" file. Copy the path to this file in <YOUR_PATH>.
At the end you have
ord --cookie-file <YOUR_PATH> --rpc-url "<RPC>"

**Comment by liuxhu** [comment] 2023-02-09 07:29
use --cookie-file but always error:
error: JSON-RPC error: transport error: unexpected HTTP code: 401

**Comment by JWMatheo** [comment] 2023-02-09 08:41
The HyperText Transfer Protocol (HTTP) 401 Unauthorized response status code indicates that the client request has not been completed because it lacks valid authentication credentials for the requested resource.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

Give you the permission or try another node

**Comment by merc1er** [comment] 2023-02-09 15:50
> before --rpc-url, you have to put --cookie-file "<YOUR_PATH>".
> To find the path you have to launch bitcoind then go to the folder where the Blockchain is stored. You'll see a ".cookie" file. Copy the path to this file in <YOUR_PATH>.
> At the end you have
> ord --cookie-file <YOUR_PATH> --rpc-url ""

I am using a remote RPC node (https://chainstack.com). Is there no way to use such a node? Surely most people don't run their own node.

**Comment by raphjaph** [comment] 2023-02-09 21:12
The cookie file is just the `rpc_user:rpc_password` concatenated like this and saved to a file, which you can point `ord` to with `--cookie-file`. On the remote instance you can generate credentials and put them in that instance's `bitcoin.conf` with the script found here https://github.com/bitcoin/bitcoin/tree/master/share/rpcauth.

**Comment by bentatum** [comment] 2023-02-09 22:24
I tried this and I'm still getting a 401.

```
ord --cookie-file ".cookie" --rpc-url http://umbrel.local:8332 info
error: JSON-RPC error: transport error: unexpected HTTP code: 401
```

.cookie looks like this
```
username:password
```

**Comment by raphjaph** [comment] 2023-02-09 22:27
Where does `username` and `password` come from? Is that from umbrel or Bitcoin Core?

**Comment by bentatum** [comment] 2023-02-09 22:29
umbrel

<img width="594" alt="Screen Shot 2023-02-09 at 5 28 48 PM" src="https://user-images.githubusercontent.com/4211826/217953767-7b5d24c2-aecf-4fba-9be9-b67689bae8b6.png">

**Comment by raphjaph** [comment] 2023-02-09 23:06
In your cookie file make sure that there is no space and new line after the `username:password`

**Comment by saraspaudel** [comment] 2023-02-10 01:04
I tried it and getting a 400

**Comment by merc1er** [comment] 2023-02-10 02:38
> The cookie file is just the `rpc_user:rpc_password` concatenated like this and saved to a file, which you can point `ord` to with `--cookie-file`. On the remote instance you can generate credentials and put them in that instance's `bitcoin.conf` with the script found here https://github.com/bitcoin/bitcoin/tree/master/share/rpcauth.

I did exactly this and got a 400 (cc @JWMatheo).

**Comment by sajshuai** [comment] 2023-02-10 07:46
> Works for other wallets. I'm sure I'm doing something wrong, though.



> I tried this and I'm still getting a 401.
> 
> ```
> ord --cookie-file ".cookie" --rpc-url http://umbrel.local:8332 info
> error: JSON-RPC error: transport error: unexpected HTTP code: 401
> ```
> 
> .cookie looks like this
> 
> ```
> username:password
> ```

I also encountered the same problem. There is no new line in the cookie file in vim, but there is a new line when I use vscode to view it remotely. I removed the new line and it worked

**Comment by merc1er** [comment] 2023-02-10 08:23
> In your cookie file make sure that there is no space and new line after the `username:password`

I can confirm there is no space and no new line in my .cookie file (I ran `cat -e .cookie` and did not see a `$`). I am still getting a 400.

**Comment by sajshuai** [comment] 2023-02-10 08:32
> > In your cookie file make sure that there is no space and new line after the `username:password`
> 
> I can confirm there is no space and no new line in my .cookie file (I ran `cat -e .cookie` and did not see a `$`). I am still getting a 400.

I got 401 caused by a new line in the cookie file, I have never encountered 400

**Comment by merc1er** [comment] 2023-02-10 09:05
> > > In your cookie file make sure that there is no space and new line after the `username:password`
> 
> > 
> 
> > I can confirm there is no space and no new line in my .cookie file (I ran `cat -e .cookie` and did not see a `$`). I am still getting a 400.
> 
> 
> 
> I got 401 caused by a new line in the cookie file, I have never encountered 400

Right, I suspect this is an issue with the ord software.

**Comment by james-global-liquidity** [comment] 2023-02-10 16:24
I'm also stuck at this same place - with the 401 error. Are we that early on this such that no one with an Umbrel is running ord yet?

**Comment by james-global-liquidity** [comment] 2023-02-10 16:42
I got it working! It turns out that just deleting the newline in nano didn't really remove it. For anyone having the 401 error, try doing this: (My .cookie is in my ord dir)

truncate -s -1 ./.cookie

This will remove the trailing newline that is causing the error.


Then run ord. Mine started indexing blocks right away. (I don't think you need the first ./ but that's exactly what I used and it worked.

**Comment by bitdeep** [comment] 2023-02-10 23:11
> I got it working! It turns out that just deleting the newline in nano didn't really remove it. For anyone having the 401 error, try doing this: (My .cookie is in my ord dir)
> 
> truncate -s -1 ./.cookie
> 
> This will remove the trailing newline that is causing the error.
> 
> Then run ord. Mine started indexing blocks right away. (I don't think you need the first ./ but that's exactly what I used and it worked.

Exactly, if you are using vim to edit the cookie file it not going to work, use the command above to truncate the file and ord will work.

**Comment by raphjaph** [comment] 2023-02-13 17:25
Closing, since this seemed to fix it. Reopen/comment if you still get an error

**Closed by raphjaph** 2023-02-13 17:25 UTC

**Comment by merc1er** [comment] 2023-02-14 02:35
> Closing, since this seemed to fix it. Reopen/comment if you still get an error

This was not fixed? The 401 issue isn't related to my issue.

**Comment by raphjaph** [comment] 2023-02-14 19:46
I think the problem is that you are connecting via `https`. Does using `bitcoin-cli` with your rpc endpoint work? 

We do not support connecting to Bitcoin Core with TLS/SSL at the moment, so you will have to use a local node.

**Comment by bensig** [comment] 2023-02-27 22:10
Having the same issues here, opened a new ticket but wanted to comment here as well. 

Remote bitcoin node works with bitcoin-cli over SSH tunnel (rpcurl=127.0.0.1:8332)

Created a cookie on the remote instance (where bitcoind is running) 

Tried to add the cookie to my local (where I am running `ord`) and I get a 401 error when I try to connect to the remote instance over an SSH tunnel to localhost:8332

```
$ord --cookie-file ~/.bitcoin/.cookie --rpc-url 127.0.0.1:8332 info
error: JSON-RPC error: transport error: unexpected HTTP code: 401
```
Full comments in my other (open) issue: https://github.com/casey/ord/issues/1849

**Comment by zx0922** [comment] 2023-02-28 19:54
P:\ord>ord --cookie-file .cookie --rpc-url 192.168.2.222 --data-dir P:\ord wallet balance
error: JSON-RPC error: transport error: unexpected HTTP code: 403

.cookies file is like username:password

ord 0.5.1

**Comment by stevel408** [comment] 2023-03-08 07:43
Quick report from my own experience, as I kept getting the 401 error after following all the instructions above on a Mac computer. It looks like the `ord` program doesn't parse the cookie file on my Mac very well. I see a Newline character in my cookie file (and any text file on Mac for that matter):

```
$ cat bitcoind_cookie
__cookie__:f450e3c95... ...516d2f3ab
```

Here's how I look at each of the characters in the file:
```
$ cat bitcoind_cookie | od -a
0000000    _   _   c   o   o   k   i   e   _   _   :   f   4   5   0   e
... ...
0000100    2   c   5   1   6   d   2   f   3   a   b  nl
0000114
```

There's clearly a newline character at the end, so I trimmed it off like this:
```
$ cat bitcoind_cookie | tr -d '\n' | od -a
0000000    _   _   c   o   o   k   i   e   _   _   :   f   4   5   0   e
... ...
0000060    3   d   9   6   3   a   9   e   5   7   5   8   e   2   7   b
0000100    2   c   5   1   6   d   2   f   3   a   b
0000113

$ cat bitcoind_cookie | tr -d '\n' > cookie2
```

Then I used the `cookie2` file for `ord` and everything starts to run perfectly.
